### ISSUE TITLE
Inplace upgrade

### ISSUE THREAD

**Issue by Leothelearner** [ChayScripts/Citrix-VDA-Upgrade-Scripts#1]
Hello , 
We are trying to do a inplace upgrade for our VDA which means installing on top of the existing ones. 
I have modified the script just to install. However , the task is not getting triggered at startup . 
Also , the machines needs multiple reboot when VDA is installing. Unfortunately , its not rebooting.

Could you please assist what needs to be changed.

Thanks

**Comment by ChayScripts** [comment]
Hi, You should first remove the existing VDA and then install another one. Follow the Readme as is, you will not have any issues.
